-- 02_tpch_views.sql
-- TPCH Sample Data Views
-- Creates views on top of Snowflake's sample TPCH data
-- Assumes SNOWFLAKE_SAMPLE_DATA database is available

USE DATABASE TPCH_DASHBOARDS;
USE SCHEMA PUBLIC;

-- View for customer information with region details
CREATE OR REPLACE VIEW V_CUSTOMER_DETAILS AS
SELECT 
    c.C_CUSTKEY,
    c.C_NAME,
    c.C_ADDRESS,
    c.C_PHONE,
    c.C_ACCTBAL,
    c.C_MKTSEGMENT,
    c.C_COMMENT,
    n.N_NAME as NATION,
    r.R_NAME as REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY;

-- View for order details with customer information
CREATE OR REPLACE VIEW V_ORDER_DETAILS AS
SELECT 
    o.O_ORDERKEY,
    o.O_CUSTKEY,
    c.C_NAME as CUSTOMER_NAME,
    c.C_MKTSEGMENT as MARKET_SEGMENT,
    o.O_ORDERSTATUS,
    o.O_TOTALPRICE,
    o.O_ORDERDATE,
    o.O_ORDERPRIORITY,
    o.O_CLERK,
    o.O_SHIPPRIORITY,
    n.N_NAME as NATION,
    r.R_NAME as REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY;

-- View for line item details with product and supplier information
CREATE OR REPLACE VIEW V_LINEITEM_DETAILS AS
SELECT 
    l.L_ORDERKEY,
    l.L_PARTKEY,
    l.L_SUPPKEY,
    l.L_LINENUMBER,
    l.L_QUANTITY,
    l.L_EXTENDEDPRICE,
    l.L_DISCOUNT,
    l.L_TAX,
    l.L_RETURNFLAG,
    l.L_LINESTATUS,
    l.L_SHIPDATE,
    l.L_COMMITDATE,
    l.L_RECEIPTDATE,
    l.L_SHIPINSTRUCT,
    l.L_SHIPMODE,
    p.P_NAME as PART_NAME,
    p.P_TYPE as PART_TYPE,
    p.P_SIZE as PART_SIZE,
    p.P_BRAND as PART_BRAND,
    s.S_NAME as SUPPLIER_NAME,
    sn.N_NAME as SUPPLIER_NATION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART p ON l.L_PARTKEY = p.P_PARTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER s ON l.L_SUPPKEY = s.S_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION sn ON s.S_NATIONKEY = sn.N_NATIONKEY;

-- View for supplier details with nation and region
CREATE OR REPLACE VIEW V_SUPPLIER_DETAILS AS
SELECT 
    s.S_SUPPKEY,
    s.S_NAME,
    s.S_ADDRESS,
    s.S_PHONE,
    s.S_ACCTBAL,
    s.S_COMMENT,
    n.N_NAME as NATION,
    r.R_NAME as REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER s
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON s.S_NATIONKEY = n.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY;
