-- 03_aggregations.sql
-- TPCH KPI Aggregations and Metrics
-- Creates views with pre-calculated metrics for dashboards

USE DATABASE TPCH_DASHBOARDS;
USE SCHEMA PUBLIC;

-- Monthly revenue by region
CREATE OR REPLACE VIEW V_MONTHLY_REVENUE_BY_REGION AS
SELECT 
    DATE_TRUNC('MONTH', O_ORDERDATE) as ORDER_MONTH,
    REGION,
    COUNT(DISTINCT O_ORDERKEY) as ORDER_COUNT,
    SUM(O_TOTALPRICE) as TOTAL_REVENUE,
    AVG(O_TOTALPRICE) as AVG_ORDER_VALUE,
    COUNT(DISTINCT O_CUSTKEY) as CUSTOMER_COUNT
FROM V_ORDER_DETAILS
GROUP BY DATE_TRUNC('MONTH', O_ORDERDATE), REGION
ORDER BY ORDER_MONTH DESC, TOTAL_REVENUE DESC;

-- Top customers by revenue
CREATE OR REPLACE VIEW V_TOP_CUSTOMERS AS
SELECT 
    O_CUSTKEY,
    CUSTOMER_NAME,
    NATION,
    REGION,
    MARKET_SEGMENT,
    COUNT(DISTINCT O_ORDERKEY) as ORDER_COUNT,
    SUM(O_TOTALPRICE) as TOTAL_REVENUE,
    AVG(O_TOTALPRICE) as AVG_ORDER_VALUE,
    MAX(O_ORDERDATE) as LAST_ORDER_DATE
FROM V_ORDER_DETAILS
GROUP BY O_CUSTKEY, CUSTOMER_NAME, NATION, REGION, MARKET_SEGMENT
ORDER BY TOTAL_REVENUE DESC;

-- Product performance metrics
CREATE OR REPLACE VIEW V_PRODUCT_PERFORMANCE AS
SELECT 
    L_PARTKEY,
    PART_NAME,
    PART_TYPE,
    PART_BRAND,
    COUNT(DISTINCT L_ORDERKEY) as ORDER_COUNT,
    SUM(L_QUANTITY) as TOTAL_QUANTITY_SOLD,
    SUM(L_EXTENDEDPRICE) as GROSS_REVENUE,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) as NET_REVENUE,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT) * (1 + L_TAX)) as TOTAL_REVENUE_WITH_TAX,
    AVG(L_DISCOUNT) as AVG_DISCOUNT_RATE
FROM V_LINEITEM_DETAILS
GROUP BY L_PARTKEY, PART_NAME, PART_TYPE, PART_BRAND
ORDER BY NET_REVENUE DESC;

-- Supplier performance metrics
CREATE OR REPLACE VIEW V_SUPPLIER_PERFORMANCE AS
SELECT 
    L_SUPPKEY,
    SUPPLIER_NAME,
    SUPPLIER_NATION,
    COUNT(DISTINCT L_ORDERKEY) as ORDER_COUNT,
    SUM(L_QUANTITY) as TOTAL_QUANTITY_SUPPLIED,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) as NET_REVENUE,
    AVG(DATEDIFF(day, L_SHIPDATE, L_RECEIPTDATE)) as AVG_DELIVERY_DAYS,
    SUM(CASE WHEN L_COMMITDATE < L_RECEIPTDATE THEN 1 ELSE 0 END) as LATE_DELIVERIES,
    COUNT(*) as TOTAL_DELIVERIES
FROM V_LINEITEM_DETAILS
WHERE L_SHIPDATE IS NOT NULL AND L_RECEIPTDATE IS NOT NULL
GROUP BY L_SUPPKEY, SUPPLIER_NAME, SUPPLIER_NATION
ORDER BY NET_REVENUE DESC;

-- Order status summary
CREATE OR REPLACE VIEW V_ORDER_STATUS_SUMMARY AS
SELECT 
    O_ORDERSTATUS,
    DATE_TRUNC('YEAR', O_ORDERDATE) as ORDER_YEAR,
    REGION,
    COUNT(DISTINCT O_ORDERKEY) as ORDER_COUNT,
    SUM(O_TOTALPRICE) as TOTAL_REVENUE,
    AVG(O_TOTALPRICE) as AVG_ORDER_VALUE
FROM V_ORDER_DETAILS
GROUP BY O_ORDERSTATUS, DATE_TRUNC('YEAR', O_ORDERDATE), REGION
ORDER BY ORDER_YEAR DESC, TOTAL_REVENUE DESC;

-- Market segment analysis
CREATE OR REPLACE VIEW V_MARKET_SEGMENT_ANALYSIS AS
SELECT 
    MARKET_SEGMENT,
    REGION,
    COUNT(DISTINCT O_CUSTKEY) as CUSTOMER_COUNT,
    COUNT(DISTINCT O_ORDERKEY) as ORDER_COUNT,
    SUM(O_TOTALPRICE) as TOTAL_REVENUE,
    AVG(O_TOTALPRICE) as AVG_ORDER_VALUE,
    SUM(O_TOTALPRICE) / COUNT(DISTINCT O_CUSTKEY) as REVENUE_PER_CUSTOMER
FROM V_ORDER_DETAILS
GROUP BY MARKET_SEGMENT, REGION
ORDER BY TOTAL_REVENUE DESC;

-- Shipping mode analysis
CREATE OR REPLACE VIEW V_SHIPPING_MODE_ANALYSIS AS
SELECT 
    L_SHIPMODE,
    COUNT(DISTINCT L_ORDERKEY) as ORDER_COUNT,
    SUM(L_QUANTITY) as TOTAL_QUANTITY,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) as NET_REVENUE,
    AVG(DATEDIFF(day, L_SHIPDATE, L_RECEIPTDATE)) as AVG_DELIVERY_DAYS,
    SUM(CASE WHEN L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) as RETURN_COUNT,
    COUNT(*) as TOTAL_SHIPMENTS
FROM V_LINEITEM_DETAILS
WHERE L_SHIPDATE IS NOT NULL AND L_RECEIPTDATE IS NOT NULL
GROUP BY L_SHIPMODE
ORDER BY NET_REVENUE DESC;
