-- 05_grants.sql
-- Security Grants and Permissions
-- Sets up role-based access control for the TPCH dashboards

USE DATABASE TPCH_DASHBOARDS;
USE SCHEMA PUBLIC;

-- Create custom roles for different access levels
-- Note: Adjust these based on your organization's needs

-- Role for analysts who need read-only access to dashboards
CREATE ROLE IF NOT EXISTS DASHBOARD_ANALYST_ROLE
    COMMENT = 'Read-only access to TPCH dashboard views and aggregations';

-- Role for data engineers who need full access to manage dashboard objects
CREATE ROLE IF NOT EXISTS DASHBOARD_ENGINEER_ROLE
    COMMENT = 'Full access to create and manage TPCH dashboard objects';

-- Grant usage on database and schema to analyst role
GRANT USAGE ON DATABASE TPCH_DASHBOARDS TO ROLE DASHBOARD_ANALYST_ROLE;
GRANT USAGE ON SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ANALYST_ROLE;

-- Grant usage on warehouse to analyst role
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE DASHBOARD_ANALYST_ROLE;

-- Grant SELECT on all views to analyst role
GRANT SELECT ON ALL VIEWS IN SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ANALYST_ROLE;

-- Grant future view access (for views created after this script runs)
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ANALYST_ROLE;

-- Grant usage on database and schema to engineer role
GRANT USAGE ON DATABASE TPCH_DASHBOARDS TO ROLE DASHBOARD_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant full access on schema to engineer role
GRANT ALL PRIVILEGES ON SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant operate on warehouse to engineer role
GRANT OPERATE, USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant SELECT, INSERT, UPDATE, DELETE on all tables to engineer role
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant SELECT on all views to engineer role
GRANT SELECT ON ALL VIEWS IN SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant privileges on future tables to engineer role
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant privileges on future views to engineer role
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TPCH_DASHBOARDS.PUBLIC TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant access to sample data (source for our views)
GRANT USAGE ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE DASHBOARD_ANALYST_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 TO ROLE DASHBOARD_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 TO ROLE DASHBOARD_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 TO ROLE DASHBOARD_ANALYST_ROLE;

GRANT USAGE ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE DASHBOARD_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 TO ROLE DASHBOARD_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 TO ROLE DASHBOARD_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant EXECUTE on tasks to engineer role (if tasks are uncommented in 04_tasks.sql)
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Grant roles to SYSADMIN (best practice for role hierarchy)
GRANT ROLE DASHBOARD_ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE DASHBOARD_ENGINEER_ROLE TO ROLE SYSADMIN;

-- Grant analyst role to engineer role (engineers have all analyst permissions)
GRANT ROLE DASHBOARD_ANALYST_ROLE TO ROLE DASHBOARD_ENGINEER_ROLE;

-- Example: Grant roles to specific users (uncomment and modify as needed)
-- GRANT ROLE DASHBOARD_ANALYST_ROLE TO USER analyst_user;
-- GRANT ROLE DASHBOARD_ENGINEER_ROLE TO USER engineer_user;

-- Display granted privileges
SHOW GRANTS TO ROLE DASHBOARD_ANALYST_ROLE;
SHOW GRANTS TO ROLE DASHBOARD_ENGINEER_ROLE;

SELECT 'Security grants applied successfully' as STATUS;
